version: '3.8'
services:

  database: 
    volumes:
        - ./database/data:/data
      # - pgdatasource:/var/lib/postgresql/data
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=my_db
  
  api:
    build: ./back-end
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:pass@database/my_db
      - NODE_ENV=production
    depends_on:
      - database

  frontend:
    build: ./client
    ports:
      - "3001:3001"
    depends_on:
      - api

volumes:
  pgdatasource:
  postgres-data:
  mongodb_data: